name: TEST - Website Screenshot and Upload to GDrive

on:
  schedule:
    - cron: '*/10 6 * * *'
  workflow_dispatch:

jobs:
  capture-and-upload:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install selenium pytz google-api-python-client google-auth-httplib2 google-auth-oauthlib

      - name: Install Google Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable

      - name: Install Chinese Fonts
        run: sudo apt-get install -y fonts-noto-cjk

      - name: Create Google Drive Token from Secret
        # This step creates the token.json file for the script to use
        run: echo '${{ secrets.GDRIVE_OAUTH_TOKEN }}' > token.json

      - name: Run script to capture and upload
        env:
          # Make sure this is a folder ID from your personal "My Drive"
          GDRIVE_FOLDER_ID: ${{ secrets.GDRIVE_FOLDER_ID }}
        run: python bp_screencap.py

      - name: Upload screenshot artifact (optional backup)
        uses: actions/upload-artifact@v4
        with:
          name: bastille-post-screenshot
          path: ./*.png
