name: TEST - Website Screenshot and Upload to GDrive

on:
  schedule:
    # Runs every 10 minutes, between 2:00 PM and 3:00 PM HKT (which is 06:00 to 06:59 UTC).
    - cron: '*/10 6 * * *'
  workflow_dispatch: # Allows you to run this workflow manually from the Actions tab

jobs:
  capture-and-upload:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install selenium pytz google-api-python-client google-auth-httplib2 google-auth-oauthlib

      - name: Install Google Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable

      - name: Install Chinese Fonts
        run: sudo apt-get install -y fonts-noto-cjk

      - name: Authenticate to Google Drive
        run: echo "${{ secrets.GDRIVE_CREDENTIALS }}" > credentials.json

      - name: Run script to capture and upload
        env:
          GDRIVE_FOLDER_ID: ${{ secrets.GDRIVE_FOLDER_ID }}
        run: python bp_screencap.py

      - name: Upload screenshot artifact (optional backup)
        uses: actions/upload-artifact@v4
        with:
          name: bastille-post-screenshot
          path: ./*.png # Uploads any .png file from the root directory
