# .github/workflows/verify_workflow.yml
name: Verify Screenshot Upload

on:
  schedule:
    # Runs daily at 5:00 PM HKT (9:00 UTC)
    - cron: '0 9 * * *'
  workflow_dispatch: # Allows manual triggering

jobs:
  verify-and-notify:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install google-api-python-client google-auth-httplib2 google-auth-oauthlib pytz sendgrid

      - name: Create Google Drive Token from Secret
        run: echo '${{ secrets.GDRIVE_OAUTH_TOKEN }}' > token.json

      - name: Run verification script
        env:
          GDRIVE_FOLDER_ID: ${{ secrets.GDRIVE_FOLDER_ID }}
          COLLEAGUE_EMAIL: ${{ secrets.COLLEAGUE_EMAIL }}
          SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
          SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}
        run: python verify_gdrive.py
