# .github/workflows/verify_workflow.yml
name: Verify Screenshot Upload

on:
  schedule:
    # Runs daily at a time of your choosing. This example is for 5:00 PM HKT (9:00 UTC).
    - cron: '0 9 * * *'
  workflow_dispatch: # Allows you to trigger it manually from the Actions tab

jobs:
  verify-and-notify:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        # Note: sendgrid is removed from this list
        run: |
          python -m pip install --upgrade pip
          pip install google-api-python-client google-auth-httplib2 google-auth-oauthlib pytz
      
      - name: Ensure fresh Google token
        run: rm -f token.json

      - name: Log Python date/time (UTC and HKT)
        run: |
          python -c "from datetime import datetime
          import pytz
          print('UTC:', datetime.utcnow())
          print('HKT:', datetime.now(pytz.timezone('Asia/Hong_Kong')))"
          print("Query being used:", query)
          print("API results:", results)


      - name: Create Google Drive Token from Secret
        # This step uses your master token secret
        run: echo '${{ secrets.GDRIVE_OAUTH_TOKEN }}' > token.json

      - name: Run verification script
        env:
          GDRIVE_FOLDER_ID: ${{ secrets.GDRIVE_FOLDER_ID }}
          COLLEAGUE_EMAIL: ${{ secrets.COLLEAGUE_EMAIL }}
          SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }} # Your Gmail address
        run: python verify_gdrive.py
